return {
	Title = "龙岛忠仆SSR",
	Version = 3,
	BackendPlugins = {"LongDaoSSR.dll"}, 
	Author = "Naced",
	Description = "龙岛忠仆加强版: 30恩义买不了吃亏买不了上当啦！可自定义忠仆，方便减少SL，寻找继承人/打工人 源码：https://github.com/NacedWang/Taiwu_LongDaoSSR_new",
	Cover = "logo.png",
	DefaultSettings = {
		{
			Key = "SameMorality",
			SettingType = "Toggle",
			DisplayName = "与太吾同立场",
			Description = "与太吾同立场",
			DefaultValue = true,
		},
		{
			Key = "SameGender",
			SettingType = "Toggle",
			DisplayName = "与太吾同性别",
			Description = "与太吾同性别",
			DefaultValue = false,
		},
		{
			Key = "FeatureDream",
			SettingType = "Toggle",
			DisplayName = "梦境中人",
			Description = "获取梦境中人特质",
			DefaultValue = true,
		},
		{
			Key = "FeatureBattle",
			SettingType = "Toggle",
			DisplayName = "神锋敛彩",
			Description = "获取神锋敛彩特质",
			DefaultValue = true,
		},
		{
			Key = "FeatureRead",
			SettingType = "Toggle",
			DisplayName = "璞玉韬光",
			Description = "获取璞玉韬光特质",
			DefaultValue = true,
		},
		{
			Key = "FeatureOld",
			SettingType = "Toggle",
			DisplayName = "服芝食玉",
			Description = "获取服芝食玉特质",
			DefaultValue = true,
		},
		{
			Key = "FeatureDao",
			SettingType = "Toggle",
			DisplayName = "经文祝祷",
			Description = "获取经文祝祷特质",
			DefaultValue = true,
		},
		{
			Key = "FeatureDead",
			SettingType = "Toggle",
			DisplayName = "活死人",
			Description = "获取活死人特质（仅特质）",
			DefaultValue = true,
		},
		{
			Key = "SkillAdd",
			DisplayName = "资质加成",
			Description = "忠仆的各项资质会基于太吾获得加成（百分比）",
			SettingType = "Slider",
			DefaultValue = 10,
			MinValue = 0,
			MaxValue = 100,
			StepSize = 10,
		},
		{
			Key = "SkillMin",
			DisplayName = "资质最小值",
			Description = "忠仆的资质最小值",
			SettingType = "Slider",
			DefaultValue = 50,
			MinValue = 0,
			MaxValue = 120,
			StepSize = 10,
		},
			{
			Key = "SkillRandom",
			DisplayName = "资质随机量",
			Description = "忠仆的资质会随机增加，数值为0-设置值",
			SettingType = "Slider",
			DefaultValue = 40,
			MinValue = 0,
			MaxValue = 120,
			StepSize = 10,
		},
		{
			Key = "BasicFeatures",
			DisplayName = "特质数",
			Description = "忠仆可获得的特质数，不会获得负面特质",
			SettingType = "Slider",
			DefaultValue = 0,
			MinValue = 0,
			MaxValue = 10,
			StepSize = 1,
		},
		{
			Key = "HusbandOrWife",
			SettingType = "Toggle",
			DisplayName = "与太吾成为夫妻",
			Description = "与太吾成为夫妻（注：会出现击剑情况QAQ）",
			DefaultValue = false,
		},
	}
}